##### plotting mass by date for each tree taxa #####

Alder <-  subset(cater_habitat, tree.species=="Alder")
Ash <-  subset(cater_habitat, tree.species=="Ash")
Beech <-  subset(cater_habitat, tree.species=="Beech")
Birch <-  subset(cater_habitat, tree.species=="Birch")
Elm <-  subset(cater_habitat, tree.species=="Elm")
Hazel <-  subset(cater_habitat, tree.species=="Hazel")
Oak <-  subset(cater_habitat, tree.species=="Oak")
Rowan <-  subset(cater_habitat, tree.species=="Rowan")
Sycamore <-  subset(cater_habitat, tree.species=="Sycamore")
Willow <-  subset(cater_habitat, tree.species=="Willow")
par(mfrow=c(1,1))
plot(cater_habitat$date, exp(cater_habitat$logmpc1), xlab="Date", ylab="Mass (g)", pch=20, col="grey")
points(cater_habitat$date, exp(cater_habitat$logmpc2), col=1, pch=20)
points(predday,exp(meanslope), type="l", lwd=2, col="red")
legend("topleft", legend="All", bty="n")

par(mfrow=c(5,2), oma=c(2,0,0,0), mar=c(2,3,1,1))
plot(Alder$date, exp(Alder$logmpc1), ylim=c(0,0.7), xlab="Date", ylab="Mass (g)", pch=20, col="grey")
points(Alder$date, exp(Alder$logmpc2), col=1, pch=20)
points(predday,exp(alder), type="l", lwd=2, col=4)
legend("topleft", legend="Alder", bty="n")

plot(Ash$date, exp(Ash$logmpc1), ylim=c(0,0.7), xlab="Date", ylab="Mass (g)", pch=20, col="grey")
points(Ash$date, exp(Ash$logmpc2), col=1, pch=20)
points(predday,exp(ash), type="l", lwd=2, col=4)
legend("topleft", legend="Ash", bty="n")

plot(Beech$date, exp(Beech$logmpc1), ylim=c(0,0.7), xlab="Date", ylab="Mass (g)", pch=20, col="grey")
points(Beech$date, exp(Beech$logmpc2), col=1, pch=20)
points(predday,exp(beech), type="l", lwd=2, col=4)
legend("topleft", legend="Beech", bty="n")

plot(Birch$date, exp(Birch$logmpc1), ylim=c(0,0.7), xlab="Date", ylab="Mass (g)", pch=20, col="grey")
points(Birch$date, exp(Birch$logmpc2), col=1, pch=20)
points(predday,exp(birch), type="l", lwd=2, col=4)
legend("topleft", legend="Birch", bty="n")

plot(Elm$date, exp(Elm$logmpc1), ylim=c(0,0.7), xlab="Date", ylab="Mass (g)", pch=20, col="grey")
points(Elm$date, exp(Elm$logmpc2), col=1, pch=20)
points(predday,exp(elm), type="l", lwd=2, col=4)
legend("topleft", legend="Elm", bty="n")

plot(Hazel$date, exp(Hazel$logmpc1), ylim=c(0,0.7), xlab="Date", ylab="Mass (g)", pch=20, col="grey")
points(Hazel$date, exp(Hazel$logmpc2), col=1, pch=20)
points(predday,exp(hazel), type="l", lwd=2, col=4)
legend("topleft", legend="Hazel", bty="n")

plot(Oak$date, exp(Oak$logmpc1), ylim=c(0,0.7), xlab="Date", ylab="Mass (g)", pch=20, col="grey")
points(Oak$date, exp(Oak$logmpc2), col=1, pch=20)
points(predday,exp(oak), type="l", lwd=2, col=4)
legend("topleft", legend="Oak", bty="n")

plot(Rowan$date, exp(Rowan$logmpc1), ylim=c(0,0.7), xlab="Date", ylab="Mass (g)", pch=20, col="grey")
points(Rowan$date, exp(Rowan$logmpc2), col=1, pch=20)
points(predday,exp(rowan), type="l", lwd=2, col=4)
legend("topleft", legend="Rowan", bty="n")

plot(Sycamore$date, exp(Sycamore$logmpc1), ylim=c(0,0.7), xlab="Date", ylab="Mass (g)", pch=20, col="grey")
points(Sycamore$date, exp(Sycamore$logmpc2), col=1, pch=20)
points(predday,exp(sycamore), type="l", lwd=2, col=4)
legend("topleft", legend="Sycamore", bty="n")

plot(Willow$date, exp(Willow$logmpc1), ylim=c(0,0.7), xlab="Date", ylab="Mass (g)", pch=20, col="grey")
points(Willow$date, exp(Willow$logmpc2), col=1, pch=20)
points(predday,exp(willow), type="l", lwd=2, col=4)
legend("topleft", legend="Willow", bty="n")

#### Checking max date with caterpillar for each taxa
cater_habitat2 <- cater_habitat_1719
cater_habitat2$caterpillars <- as.character(cater_habitat2$caterpillars)
cater_habitat2 <- subset(cater_habitat2, caterpillars!="0")
cater_habitat2$caterpillars <- as.numeric(cater_habitat2$caterpillars) 
Alder <-  subset(cater_habitat2, tree.species=="Alder")
Ash <-  subset(cater_habitat2, tree.species=="Ash")
Beech <-  subset(cater_habitat2, tree.species=="Beech")
Birch <-  subset(cater_habitat2, tree.species=="Birch")
Elm <-  subset(cater_habitat2, tree.species=="Elm")
Hazel <-  subset(cater_habitat2, tree.species=="Hazel")
Oak <-  subset(cater_habitat2, tree.species=="Oak")
Rowan <-  subset(cater_habitat2, tree.species=="Rowan")
Sycamore <-  subset(cater_habitat2, tree.species=="Sycamore")
Willow <-  subset(cater_habitat2, tree.species=="Willow")

#range('taxa'$date)

##### histograms of dates with caterpillars for each taxa
par(mfrow=c(5,2), oma=c(2,0,0,0), mar=c(2,3,1,1))
hist(Alder$date, breaks=100, xlim=c(117,172))
hist(Ash$date, breaks=100, xlim=c(117,172))
hist(Beech$date, breaks=100, xlim=c(117,172))
hist(Birch$date, breaks=100, xlim=c(117,172))
hist(Elm$date, breaks=100, xlim=c(117,172))
hist(Hazel$date, breaks=100, xlim=c(117,172))
hist(Oak$date, breaks=100, xlim=c(117,172))
hist(Rowan$date, breaks=100, xlim=c(117,172))
hist(Sycamore$date, breaks=100, xlim=c(117,172))
hist(Willow$date, breaks=100, xlim=c(117,172))
